    name: CI 

    on:
        push:
            branches:
            - main
  
    jobs:
        build:
            name: 'Build and Push'
            runs-on: ubuntu-latest

            steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.x'
              
            - name: Run tests
              run: go test 

            - name: Get Commit Hash
              id: commit_hash
              run: |
                SHA=$(echo $GITHUB_SHA | head -c7)
                echo "sha=$SHA" >> $GITHUB_OUTPUT
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}


            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: |
                  p1ngo/api-journey:${{steps.commit_hash.outputs.sha}}
                  p1ngo/api-journey:latest
